### ISSUE TITLE
The crash of the betterrecords

### ISSUE THREAD

**Issue by DD-minelong** [NicholasFeldman/BetterRecords#113]
BetterRecords: `1.6.2`  
Forge: `forge-1.12.2-14.23.5.2854`

# Issue
When I copied the song url to Record Etcher, Minecraft crashed

Caused by: java.lang.IllegalStateException: contentType must not be null
	at tech.feldman.betterrecords.client.gui.GuiRecordEtcher.updateStatus(GuiRecordEtcher.kt:311) ~[GuiRecordEtcher.class:?]
	at tech.feldman.betterrecords.client.gui.GuiRecordEtcher.func_146979_b(GuiRecordEtcher.kt:255) ~[GuiRecordEtcher.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117) ~[bmg.class:?]
	at tech.feldman.betterrecords.client.gui.GuiRecordEtcher.func_73863_a(GuiRecordEtcher.kt:335) ~[GuiRecordEtcher.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660) ~[Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457) ~[buq.class:?]
	... 9 more
[latest.log](https://github.com/NicholasFeldman/BetterRecords/files/5074240/latest.log)

**Comment by otakup0pe** [comment]
If you are willing to share the song URL what is it? From this crash looks like the webserver is sending a malformed response. Could see this convert ed to an error message rather than a crash least.

**Comment by DD-minelong** [comment]
Thank you for your help, I changed the URL and the mod can be used successfully :)
