### ISSUE TITLE
Radio playback error

### ISSUE THREAD

**Issue by IdrisQe** [NicholasFeldman/BetterRecords#65]
BetterRecords: `1.5.7`  
Forge: `14.23.4.2760`

# Issue
1. After tuning to valid frequency, inserting crystal into radio makes no sound and causes following output in the console. Repeatable.
```
[02:00:24] [Thread-30/INFO] [betterrecords]: Playing sound from stream at BlockPos{x=-390, y=68, z=-1184} in 0
[02:00:35] [Thread-30/WARN] [FML]: =============================================================
[02:00:35] [Thread-30/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[02:00:35] [Thread-30/WARN] [FML]: Offender: com/codingforcookies/betterrecords/repack/jcraft/jogg/Buffer.report(Ljava/lang/String;)V
[02:00:35] [Thread-30/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[02:00:35] [Thread-30/WARN] [FML]: =============================================================
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.io.IOException: mark/reset not supported
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.io.InputStream.reset(Unknown Source)
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.sun.media.sound.SoftMidiAudioFileReader.getAudioInputStream(Unknown Source)
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.codingforcookies.betterrecords.client.sound.SoundPlayer.playStream(SoundPlayer.kt:76)
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.codingforcookies.betterrecords.client.sound.SoundPlayer.playSoundFromStream(SoundPlayer.kt:57)
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.codingforcookies.betterrecords.client.sound.SoundManager$queueStreamAt$job$1.invoke(SoundManager.kt:29)
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.codingforcookies.betterrecords.client.sound.SoundManager$queueStreamAt$job$1.invoke(SoundManager.kt:7)
[02:00:35] [Thread-30/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```
# Steps to Reproduce
1. Tune crystal (i tried http://aroto.radio.net/ to test, said it was valid)
2. Place crystal in Radio
3. Close radio cover

Link to crash log: N/A, did not crash.

**Comment by NicholasFeldman** [comment]
The issue here was that the url you were trying to use was not an ICY format stream, and the frequency tuner was accepting any valid page as a stream.

The fix to this makes the tuner deny all urls that aren't actually streams, like the record player does.
