### ISSUE TITLE
Errors in use

### ISSUE THREAD

**Issue by wlop77** [NicholasFeldman/BetterRecords#92]
[net.minecraft.tileentity.TileEntity]: Failed to load data for block entity betterrecords:recordplayer
java.lang.NullPointerException: null
	at net.minecraft.item.Item.getEntityLifespan(Item.java:638) ~[ain.class:?]
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:68) ~[acl.class:?]
	at com.codingforcookies.betterrecords.block.tile.TileRecordPlayer.setRecord(TileRecordPlayer.kt:18) ~[TileRecordPlayer.class:?]
	at com.codingforcookies.betterrecords.block.tile.TileRecordPlayer.func_145839_a(TileRecordPlayer.kt:67) ~[TileRecordPlayer.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:128) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:498) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:git-CatServer-1.12.2-e3ad8ed]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:git-CatServer-1.12.2-e3ad8ed]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[00:47:37] [Server thread/ERROR] [FML]: A TileEntity betterrecords:recordplayer(com.codingforcookies.betterrecords.block.tile.TileRecordPlayer) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException: null
	at net.minecraft.item.Item.getEntityLifespan(Item.java:638) ~[ain.class:?]
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:68) ~[acl.class:?]
	at com.codingforcookies.betterrecords.block.tile.TileRecordPlayer.setRecord(TileRecordPlayer.kt:18) ~[TileRecordPlayer.class:?]
	at com.codingforcookies.betterrecords.block.tile.TileRecordPlayer.func_145839_a(TileRecordPlayer.kt:67) ~[TileRecordPlayer.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:128) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:498) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:git-CatServer-1.12.2-e3ad8ed]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:git-CatServer-1.12.2-e3ad8ed]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[00:47:37] [Server thread/ERROR] [net.minecraft.tileentity.TileEntity]: Failed to load data for block entity betterrecords:recordplayer
java.lang.NullPointerException: null
	at net.minecraft.item.Item.getEntityLifespan(Item.java:638) ~[ain.class:?]
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:68) ~[acl.class:?]
	at com.codingforcookies.betterrecords.block.tile.TileRecordPlayer.setRecord(TileRecordPlayer.kt:18) ~[TileRecordPlayer.class:?]
	at com.codingforcookies.betterrecords.block.tile.TileRecordPlayer.func_145839_a(TileRecordPlayer.kt:67) ~[TileRecordPlayer.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:128) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:498) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:git-CatServer-1.12.2-e3ad8ed]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:git-CatServer-1.12.2-e3ad8ed]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[00:47:37] [Server thread/ERROR] [FML]: A TileEntity betterrecords:recordplayer(com.codingforcookies.betterrecords.block.tile.TileRecordPlayer) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException: null
	at net.minecraft.item.Item.getEntityLifespan(Item.java:638) ~[ain.class:?]
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:68) ~[acl.class:?]
	at com.codingforcookies.betterrecords.block.tile.TileRecordPlayer.setRecord(TileRecordPlayer.kt:18) ~[TileRecordPlayer.class:?]
	at com.codingforcookies.betterrecords.block.tile.TileRecordPlayer.func_145839_a(TileRecordPlayer.kt:67) ~[TileRecordPlayer.class:?]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:128) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:498) [aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:git-CatServer-1.12.2-e3ad8ed]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:git-CatServer-1.12.2-e3ad8ed]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by NicholasFeldman** [comment]
Not enough information
