### ISSUE TITLE
Exception in ticking world 

### ISSUE THREAD

**Issue by IKalman** [NicholasFeldman/BetterRecords#95]
BetterRecords: 1.8.9
Forge: 1.8.9

# Exception in ticking world
I cant join my world without it crashing, when I join without forge its just a completely different world

# Steps to Reproduce
1.place jukebox and speakers
2. wire them up
3. close game

Link to crash log: <Preferably Gist or Pastebin> 
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/8/20 12:40 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagList.func_152446_a(SourceFile:66)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:132)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:82)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
	at net.minecraft.world.World.func_72964_e(World.java:287)
	at net.minecraft.world.World.func_175726_f(World.java:282)
	at net.minecraft.world.World.func_180495_p(World.java:820)
	at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:72)
	at net.minecraft.block.Block.func_180645_a(Block.java:431)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:430)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagList.func_152446_a(SourceFile:66)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:414)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:47)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:132)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:82)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
	at net.minecraft.world.World.func_72964_e(World.java:287)
	at net.minecraft.world.World.func_175726_f(World.java:282)
	at net.minecraft.world.World.func_180495_p(World.java:820)
	at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:72)
	at net.minecraft.block.Block.func_180645_a(Block.java:431)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:430)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)

-- Affected level --
Details:
	Level name: NA NA NA project
	All players: 1 total; [EntityPlayerMP['IKalman'/20, l='NA NA NA project', x=-157.18, y=74.77, z=-1271.91]]
	Chunk stats: ServerChunkCache: 948 Drop: 0
	Level seed: -2186862697415981906
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: 63.00,4.00,-996.00 - World: (63,4,-996), Chunk: (at 15,0,12 in 3,-63; contains blocks 48,0,-1008 to 63,255,-993), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Level time: 1016341 game time, 1016341 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 10124 (now: false), thunder time: 80783 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 297132120 bytes (283 MB) / 503316480 bytes (480 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	betterrecords{1.8.9-1.3.0} [Better Records] (betterrecords-1.8.9-1.3.0 (1).jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['IKalman'/20, l='NA NA NA project', x=-157.18, y=74.77, z=-1271.91]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by NicholasFeldman** [comment]
1.8.9 is no longer supported
